### ISSUE TITLE
Mailcatcher latest container does not start up correctly anymore

### ISSUE THREAD

**Issue by vbode** [spaquet/docker-alpine-mailcatcher#5]
Hi there,

It looks like the latest version of mailcatcher is not starting up correctly anymore. This is what I get when I try to run it:
```
docker run --rm -p 1080:1080 -p 1025:1025 --name mailcatcher stpaquet/alpinemailcatcher
Starting MailCatcher v0.8.2
<internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- net/smtp (LoadError)
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail.rb:9:in `<module:Mail>'
        from /usr/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail.rb:3:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.8.2/lib/mail_catcher/mail.rb:5:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.8.2/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.8.2/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
        from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.8.2/lib/mail_catcher.rb:233:in `rescue_port'
        from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.8.2/lib/mail_catcher.rb:182:in `block in run!'
        from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
        from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
        from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.8.2/lib/mail_catcher.rb:180:in `run!'
        from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.8.2/bin/mailcatcher:6:in `<top (required)>'
        from /usr/bin/mailcatcher:25:in `load'
        from /usr/bin/mailcatcher:25:in `<main>'
```

**Comment by spaquet** [comment]
Should be fixed in v1.7.8
the gem net-snmp was not set up properly during the install.
